[package]
name = "rws"
version = "0.0.12"
authors = ["Bohdan Tsap <bohdan.tsap@tutanota.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
clap = "3.0.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79" }
toml = "0.5.8"