ip = 'localhost'
port = 7888
thread_count = 2

[cors]
allow_origins = ["foo.example", "bar.example"]
allow_methods = ["POST", "PUT"]
allow_headers = ["Content-Type", "X-Custom-Header"]
allow_credentials = true
expose_headers = ["Content-Type", "X-Custom-Header"]
max_age = "523452"