# see src/test/config.toml for example configuration
ip = 'localhost'
port = 7888
thread_count = 2

[cors]
allow_origins = []
allow_methods = []
allow_headers = []
allow_credentials = false
expose_headers = []
max_age = "86400"