# see https://github.com/bohdaq/rust-web-server/blob/cors/src/test/config.toml for example configuration
ip = 'localhost'
port = 7888
thread_count = 2

[cors]
allow_all = false # true will allow all CORS requests, and you can omit setting properties below
allow_origins = ["http://localhost:7888", "http://abclocalhost:7888"] # won't apply if cors allow_all set to true
allow_methods = ["GET"] # won't apply if cors allow_all set to true
allow_headers = ["content-type"] # won't apply if cors allow_all set to true
allow_credentials = false # won't apply if cors allow_all set to true
expose_headers = ["Content-Type"] # won't apply if cors allow_all set to true
max_age = "86400" # won't apply if cors allow_all set to true