ip = '127.0.0.1'
port = 7888
thread_count = 200
client_hints = true
#  CLIENT HINTS
# Sec-CH-UA-Arch
# Sec-CH-UA-Bitness
# Sec-CH-UA-Full-Version-List
# Sec-CH-UA-Model
# Sec-CH-UA-Platform-Version
# Downlink (Mbps)
# ECT (2g/3g/4g)
# RTT (in ms, includes server processing time)

[cors]
allow_all = false # true will allow all CORS requests and you can omit configuring cors properties below
allow_origins = ["http://localhost:7888", "http://localhost:7887"] # list of allowed origins, this setting won't apply if cors allow_all set to true
allow_methods = ["GET", "DELETE", "PUT", "PATCH"] # list of allowed methods, this setting won't apply if cors allow_all set to true
allow_headers = ["content-type", "x-custom-header"] # list of allowed request headers, in lowercase, this setting won't apply if cors allow_all set to true
allow_credentials = true # if set to true, will allow to transmit credentials via CORS requests, this setting won't apply if cors allow_all set to true
expose_headers = ["content-type", "x-custom-header"] # list of allowed response headers, in lowercase, this setting won't apply if cors allow_all set to true
max_age = "86400" # in seconds, time to cache in browser CORS information, 86400s = 1 day; this setting won't apply if cors allow_all set to true
